# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-17 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20180217_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='all_rating',
            new_name='average_rating',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='nmb_rating',
            new_name='nmb_of_rating',
        ),
        migrations.AddField(
            model_name='product',
            name='sum_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.CharField(choices=[('0', 0), ('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], default='0', max_length=6),
        ),
    ]
