# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-17 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20180217_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
    ]
