# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-21 20:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0008_auto_20180219_1122'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productrating',
            unique_together=set([('product', 'user')]),
        ),
    ]
