# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-22 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20180221_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='average_rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
