# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-24 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20180224_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='average_rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
