# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-28 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20180228_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='my_id',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
