# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-28 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_product_my_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='my_id',
        ),
    ]
