# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-09 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20180309_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='productincart',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
