# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-09 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_productincart_add_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productincart',
            old_name='product_in_cart',
            new_name='product',
        ),
    ]
