# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-09 22:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20180309_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productincart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_in_cart', to=settings.AUTH_USER_MODEL),
        ),
    ]
