# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-12 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_auto_20180312_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelManagers(
            name='product',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='testmodel',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='product.Product'),
        ),
    ]
