# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-12 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_auto_20180312_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='product',
            field=models.ManyToManyField(blank=True, to='product.Product'),
        ),
    ]
