# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-12 10:21
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_auto_20180312_1016'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('active_product', django.db.models.manager.Manager()),
            ],
        ),
    ]
