# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-12 10:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_auto_20180312_1021'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
            ],
        ),
    ]
