# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-12 10:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_auto_20180312_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmodel',
            name='product',
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
