# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-12 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('product', '0028_auto_20180312_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productincart',
            name='session_key',
        ),
        migrations.AddField(
            model_name='productincart',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.Session'),
        ),
    ]
