# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-27 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_productincart_in_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productincart',
            name='in_order',
        ),
    ]
