# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-31 13:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sessions', '0001_initial'),
        ('product', '0033_remove_productincart_in_order'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productincart',
            unique_together=set([('product', 'user', 'session')]),
        ),
    ]
