# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-09 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_auto_20180331_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productincart',
            name='session',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
