# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-25 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0029_auto_20180312_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('address', models.TextField()),
                ('status', models.CharField(choices=[('Новий', 'Новий'), ('Обробка', 'Обробка'), ('Виконано', 'Виконано'), ('Скасовано', 'Скасовано')], default='Новий', max_length=10)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(to='product.ProductInCart')),
            ],
        ),
    ]
