# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-25 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_nmb',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
