# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-27 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_remove_productincart_in_order'),
        ('order', '0004_auto_20180325_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInOder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcs', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_in_order', to='product.Product')),
            ],
        ),
    ]
