# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-27 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_productinoder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinoder',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductInOder',
        ),
    ]
