# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-27 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20180327_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_order_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
