# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-27 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_total_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_order_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
